### ISSUE TITLE
Unable to set individual speaker levels when importing eiscp into .py script

### ISSUE THREAD

**Issue by mattpurnell** [miracle2k/onkyo-eiscp#104] opened 2018-12-07 07:14 UTC
Hey - great tool. I have it 80% working, and it is _excellent_ for home automation. 

Where I have come unstuck on my AVR (**TX-NR609**), is when trying to set the volume level on individual speakers/channels via the receiver.command("command value") method (I want to stick with this method to standardise the functions, outputs and variables between all moving parts of the automations).

Using the Subwoofer as an example - I can happily step the volume down by using "onkyo SWLDOWN".

Within **Python 3** however, as I run 'receiver.command("subwoofer-temporary-level DOWN") ' - I always get "('subwoofer-temporary-level', 'N/A')" as a response (unless specifying '0'), while the actual level doesn't budge. Note I have tried MANY numbers, including HEX. If I use a negative number (as is required) I just get an error:

```
>>> receiver.command('subwoofer-temporary-level', '00', zone='main')
('subwoofer-temporary-level', 0)
>>> receiver.command('subwoofer-temporary-level', '0', zone='main')
('subwoofer-temporary-level', 0)
>>> receiver.command('subwoofer-temporary-level', '5', zone='main')
('subwoofer-temporary-level', 'N/A')
>>> receiver.command('subwoofer-temporary-level', '-5', zone='main')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/eiscp/core.py", line 212, in command_to_iscp
    value = commands.VALUE_MAPPINGS[group][prefix][argument]
KeyError: '-'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/eiscp/core.py", line 472, in command
    iscp_message = command_to_iscp(command, arguments, zone)
  File "/usr/local/lib/python3.6/site-packages/eiscp/core.py", line 226, in command_to_iscp
    '"{}" in zone "{}"'.format(argument, command, zone))
ValueError: "-" is not a valid argument for command "subwoofer-temporary-level" in zone "main"

```
Trying again within **Python 2.7**:

```
>>> receiver.command('subwoofer-temporary-level UP')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "eiscp/core.py", line 479, in command
    iscp_message = command_to_iscp(command, arguments, zone)
  File "eiscp/core.py", line 228, in command_to_iscp
    return '{}{}'.format(prefix, value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 0: ordinal not in range(128)
```
I have tried to set a specific volume as well, but admittedly I can make no sense at all of the commands yml file (below) - so perhaps no surprises that I can only get errors here too, despite trying so many combinations of what's there:

```
  SWL:
    name: subwoofer-temporary-level
    description: Subwoofer (temporary) Level Command
    values:
      ? - -30
        - 24
      : name: 15-0db-0-0db-12-0db
        description: sets Subwoofer Level -15.0dB - 0.0dB - +12.0dB(0.5dB Step)
        models: set1
      ? - -15
        - 12
      : name: 15db-0db-12db
        description: sets Subwoofer Level -15dB - 0dB - +12dB
        models: set1
      "\u201CUP\u201D":
        name: up
        description: LEVEL + Key
        models: set1
      "\u201CDOWN\u201D":
        name: down
        description: "LEVEL \u2013 KEY"
        models: set1
      QSTN:
        name: query
        description: gets the Subwoofer Level
        models: set1
```

I get all these same issues with the center speaker. 

Does anyone recognise these symptoms? I would love to avoid having to dig through the source files, to get these commands working..!

**Comment by TheNetStriker** [comment] 2019-02-10 16:59
I'am currently also trying to set the level of the center speaker and it only works with a 0 value. Did you find a solution for this yet?

**Comment by mattpurnell** [comment] 2019-02-10 23:58
I ended up using NodeRed to send EISCP commands directly to the receiver; if you don't use Nodered for automation then I am not 100% sure how these commands would be sent from an SSH command for example, but there is probably a raw EISCP app somewhere.

I couldn't get it working from the Onkyo app. 


**Raw EISCP Commands**
**Channel select (cycles):**
speaker-level-calibration=CHSEL

**Channel level adjust/query:** 
speaker-level-calibration=up
speaker-level-calibration=down
speaker-level-calibration=query

**Comment by TheNetStriker** [comment] 2019-02-11 00:09
In the meantime I found out some raw commands that work. CTLUP and CTLDOWN increase and decrease the level by 0.5db. With CTL-4 and CTL04 you can set the level to plus and minus 4db. But I didn't find a way to set e.g. to level -4.5 with only one command. I only managed to get to it by sending the -4 command and then the DOWN command. Do you know a way to send this with a single command?

**Comment by mattpurnell** [comment] 2019-02-11 02:36
Afraid not, looks like you got further than me..!

But you need to select the speaker in question, right?

**Comment by TheNetStriker** [comment] 2019-02-12 09:15
No, the CTL command is always just for the center speaker level. I tried different methods of sending half db values to the receiver, but nothing worked so far. I also did some queries using the CTLQSTN command to see what value is set and when the value was e.g. set to 4.5db this query would also just return 4. In the official app it is also only possible to set the value in full steps, so I guess this is just not possible with only one command. (At least not on my TX-NR818)

I've created a litte Python script that sends the commands automatically based on the value:
```
#!/usr/bin/python3

import eiscp
import argparse
import math

parser = argparse.ArgumentParser(description="Sends commands to Onkyo receiver")
parser.add_argument("--command", dest="command", metavar="COMMAND", type=str,
                    help="Onkyo command", required=True)
parser.add_argument("--value", dest="value", metavar="VALUE", type=float,
                    help="Command value", required=True)

args = parser.parse_args()
receiver = eiscp.eISCP("192.168.1.100")

def sendRawCommand(command):
    print("Sending command " + command)
    receiver.raw(command)
    print("Command " + command + " sent")

if args.command == "center-temporary-level":
    frac, whole = math.modf(args.value)
    rawValue = str(int(whole)).zfill(2)
    rawCommand = "CTL" + rawValue

    sendRawCommand(rawCommand)

    if frac == 0.5:
        sendRawCommand("CTLUP")
    elif frac == -0.5:
        sendRawCommand("CTLDOWN")

receiver.disconnect()
```

Just call this with the argument "center-temporary-level" and the value you want to set.

**Comment by mattpurnell** [comment] 2019-02-12 09:26
Nice one! NodeRed is a limited in one respect - that it doesn't provide an option to read feedback easily, without streaming reams of data 24/7. So, I may go back to the script option again. Good to see that importing eiscp and sending raw works - cheers

**Comment by DavidSpek** [comment] 2020-11-12 12:07
To revive an old issue that is still relevant, I am wanting to be able to set the `subwoofer-temporary-level` on my TX-RZ730. What I noticed is that `onkyo --host 192.168.xxx.xxx subwoofer-temporary-level=query` worked but `UP`, `DOWN` or a value does not and gives the response `TX-RZ730: subwoofer-temporary-level = N/A`. 

The interesting thing is that the raw command `onkyo --host 192.168.xxx.xxx SWLUP` and `onkyo --host 192.168.xxx.xxx SWLDOWN` did work, but again trying to set a level did not. However, in Python I was able to set all the levels correctly. For example:
```
import eiscp
receiver = eiscp.eISCP('192.168.xxx.xxx')
receiver.raw("SWL+05")
```

Notice that the command is `SWL+05` and not `SWL05`. 
When trying to use the command `onkyo --host 192.168.xxx.xxx SWL+05` or `onkyo --host 192.168.xxx.xxx SWL-05` the follow error is returned:
`Error: Need at least command and argument`
This error is caused by the following line
https://github.com/miracle2k/onkyo-eiscp/blob/fdbad74dc5fb959f9b653e21f45b8489e5bf8140/eiscp/script.py#L125

What that line does it attempt to identify if a command that is sent is a raw command or a higher level one. It is doing this by checking if the argument that is passed is uppercase and alphanumerical. The problem with this is that the command can also contain `-` and `+` in the case of subwoofer level. I am assuming this check will also incorrectly process other commands as not being raw while they should be. Once this is fixed, it will be fairly easy to set the subwoofer temporary level from Home Assistant, or any other EISCP command. It is fairly easy to send raw EISCP commands from Home Assistant using the following method:

In the configuration.yaml, add the following (check the location of `onkyo` with the command `which onkyo` in a terminal):
```
shell_command:
  onkyo_command: /usr/local/bin/onkyo --host {{ ip }} {{ cmd }}
```
Restart Home Assistant.

Then, create a script in Home Assistant. Example: in the Sequence section:
```
Action type: Call service
Service: shell_command.onkyo_command
Service data:
ip: 192.168.xxx.xxx
cmd: SWL+5
```

**Comment by DavidSpek** [comment] 2020-11-12 14:15
I have added a pull request that fixes the identification of raw commands using a regular expression. This allows for executing the command `onkyo --host 192.168.xxx.xxx SWL+05` for example. FYI, `onkyo --host 192.168.xxx.xxx SWL00` returns N/A as zero is set with ``onkyo --host 192.168.xxx.xxx SWL000` on my receiver.

**Comment by DavidSpek** [comment] 2020-11-13 11:29
@mattpurnell @TheNetStriker Not sure if this is still relevant for you guys, but the issue in regards to subwoofer-temporary-level has been fixed in https://github.com/miracle2k/onkyo-eiscp/pull/128. Adding temporary center channel level is extremely trivial, but I think it would be more useful to create an index of all settings that need to handle positive and negative values for a lookup.

**Comment by TheNetStriker** [comment] 2020-11-13 15:18
@mattpurnell I can live with the workaround I've found, but it would be nice to be able to set the center speaker level to a decimal value using a single command instead of two.

**Comment by DavidSpek** [comment] 2020-11-13 16:18
@TheNetStriker I just added a commit for center-temporary-level anyways. Each step is 0.5 dB so you can set the level to a decimal value with one of the following commands:
`onkyo --host 192.168.xxx.xxx center-temporary-level=[-24, 24]`
`onkyo --host 192.168.xxx.xxx CTL[-18, 000, +18]` (hexadecimal values with `-` or `+`, zero is +00 or 000)
`receiver.raw('CTL[-18, 000, +18]')` (hexadecimal values with `-` or `+`, zero is +00 or 000)
`receiver.command('center-temporary-level', [-24, 24], 'main')`
`receiver.command('center-temporary-level [-24, 24]')`
`receiver.command('center-temporary-level=[-24, 24]')`

**Closed** 2020-11-18 17:57 UTC
